---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: miku-os
# description will be included in the image's metadata
description: The best distro for Miku lovers!

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: .
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - micro
        - fastfetch
        - btop
        - haruna
        - elisa
        - git
        - gwenview
        - krita
        - opentoonz
        - lmms

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - one.ablaze.floorp  # The browser
          - dev.vencord.Vesktop # Miku needs to chat 
          - online.hatsune_miku.tachidesk-vaadinui # Manga reader with a Miku logo
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: script
    scripts:
      - |
        # 1. Define our Master Miku Files (These must exist in your repo!)
        MIKU_PNG="/usr/share/icons/hicolor/48x48/apps/start-here.png"
        MIKU_SVG="/usr/share/icons/hicolor/scalable/apps/start-here.svg"

        # 2. The "Jedi Mind Trick" (Symlinking)
        # Instead of copying, we force 'ln -sf' (Link Symbolically Force).
        # This breaks the old Fedora links and points them straight to Miku.
        find /usr/share/icons -name "fedora-logo-icon.png" -exec ln -sf $MIKU_PNG {} \;
        find /usr/share/icons -name "fedora-logo-icon.svg" -exec ln -sf $MIKU_SVG {} \;
        
        # 3. Handle the "Generic" Distributor Logo too (Just to be safe)
        find /usr/share/icons -name "distributor-logo.svg" -exec ln -sf $MIKU_SVG {} \;

        # 4. Refresh Cache (Added '|| true' so it won't crash the build if it complains)
        gtk-update-icon-cache /usr/share/icons/hicolor || true
        gtk-update-icon-cache /usr/share/icons/breeze || true
