---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: miku-os
# description will be included in the image's metadata
description: The best distro for Miku lovers!

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: .
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - micro
        - fastfetch
        - btop
        - haruna
        - elisa
        - git
        - gwenview
        - krita
        - opentoonz
        - lmms

  - type: flatpaks
  image-src: https://dl.flathub.org/repo/flathub.flatpakrepo
  install:
    - one.ablaze.floorp
    - dev.vencord.Vesktop
    - online.hatsune_miku.tachidesk-vaadinui
    - io.github.vance_m.Bazaar

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: script
    scripts:
      - fix-icons.sh
      - fix-branding.sh
